### ISSUE TITLE
Replace detect-libc with isAlpine check?

### ISSUE THREAD

**Issue by vweevers** [prebuild/prebuild-install#101]
Same as in [`node-gyp-build`](https://github.com/prebuild/node-gyp-build/blob/fabd3d0dd9585b2450580b93457e418744c458b2/index.js#L11-L12), we can do:

```js
var platform = os.platform()
var libc = process.env.LIBC || (isAlpine(platform) ? 'musl' : 'glibc')

function isAlpine (platform) {
  return platform === 'linux' && fs.existsSync('/etc/alpine-release')
}
```

This is much more lightweight, see https://github.com/prebuild/node-gyp-build/pull/14#discussion_r249281742.

@lovell (as the author of #55) any objections?

**Comment by vweevers** [comment]
While we're at it, let's also read `env.npm_config_libc` to support `npm i --libc=musl`. That use case makes more sense than what we currently support (`prebuild-install --libc=musl`).

**Comment by lovell** [comment]
I think the desire is to correctly detect musl libc, of which Alpine Linux is just one consumer.

An increasing number of Linux flavours also use musl libc but won't have `/etc/alpine-release`, e.g. Void, OpenWrt.

The `existsSync` check proposed here would make a good addition to detect-libc and could occur before spawning any processes if that's a problem. Happy to accept a PR.

**Comment by vweevers** [comment]
> The `existsSync` check proposed here would make a good addition to detect-libc and could occur before spawning any processes if that's a problem

Nah, it would still spawn processes if the platform is _not_ Alpine, which is more common. And in the context of `detect-libc` it's probably more important to be correct (e.g. older Alpine does use glibc).

> An increasing number of Linux flavours also use musl libc but won't have /etc/alpine-release, e.g. Void, OpenWrt.

Roger.
