### ISSUE TITLE
is it working with npm-scope ?

### ISSUE THREAD

**Issue by toams69** [prebuild/prebuild-install#105]
Hi,

It seems when using a package with npm score (ex @toto/mypackage) the url to fetch the prebuilt is not correclty formatted.
I did some test locally, when I remove the npm scope this is working fine.

I am using .npmr to specify the remote server and a custom server (not github)

**Comment by vweevers** [comment]
> I am using .npmr to specify the remote server and a custom server (not github)

Can you share those settings?
