### ISSUE TITLE
Runtime is recognized as node instead of electron when installing Atom package on Windows

### ISSUE THREAD

**Issue by dapetcu21** [prebuild/prebuild-install#106]
I'm getting
```
prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=node arch=x64 libc= platform=win32)
```

when trying to run `apm install language-fuior` (or when trying to install the package from Atom's UI)

[`language-fuior`](https://github.com/dapetcu21/atom-language-fuior) is a package of mine that depends on [`tree-sitter-fuior`](https://github.com/dapetcu21/tree-sitter-fuior), which uses prebuild.

**Comment by vweevers** [comment]
Thinking out loud, could you or Atom set `npm_config_runtime=electron`? Without breaking other flows.

cc @shiftkey maybe you have some insights from your experience with [`registry-js`](https://github.com/desktop/registry-js) or [`fs-admin`](https://github.com/atom/fs-admin)?

**Comment by shiftkey** [comment]
@vweevers I'm not familiar with how `apm` handles native modules needed by extensions - probably worth asking about your case in this PR which seems like The Proper Fix™ for what you need https://github.com/atom/apm/pull/862

**Comment by dapetcu21** [comment]
To be honest, I don't know much about what `apm` does (or how to hijack its install process so that i can add that env var without having to release a new package version), but looking at this package's rc.js, the PR @shiftkey mentions does indeed look like it would fix the issue.

**Comment by shiftkey** [comment]
@dapetcu21 as a workaround you could try setting environment variables yourself when invoking `apm`, but I could see a scenario where something inside `apm` doesn't pass it through (the PR itself hints at that).

**Comment by vweevers** [comment]
Assuming that `language-fuior` is strictly Atom-only, you could also try adding `config: { runtime: 'electron' }` to your `package.json`.

**Comment by Aerijo** [comment]
Environment variables that are not set by apm will be passed through, at least for the [install command](https://github.com/atom/apm/blob/8f7681abb2dcbe8bc7b1fcf73d60a2890a0bfbc8/src/install.coffee#L78).

**Comment by dapetcu21** [comment]
@vweevers oh yeah. I feel dumb for not having tried that. It works if I set `npm_config_runtime=electron` before running `apm`. Thanks!

I might also try the `config: { runtime: 'electron' }` entry a bit later.

**Comment by dapetcu21** [comment]
The config thing didn't work if added to `language-fuior` and I won't add it to `tree-sitter-fuior` as that may be used outside Atom as well. Oh well, I'll just wait for that PR, I guess.

**Comment by vweevers** [comment]
Closing because there's nothing we can do here, but feel free to post follow-up questions. Thanks @shiftkey for pointing us in the right direction!
