### ISSUE TITLE
Replace require() test with non-lazy dlopen() test

### ISSUE THREAD

**Issue by vweevers** [prebuild/prebuild-install#112]
A thought. Currently, post-download, we do this test:

https://github.com/prebuild/prebuild-install/blob/a5ff6d3899af47428ef19c8212d0d49a0c4bb447/download.js#L101-L105

As I understand it, this resolves symbols lazily and may thus skip potentially conflicting or missing symbols. Could we _maybe_ do the following test instead? Would that have merit?

```
const constants = require('os').constants.dlopen
process.dlopen(module, 'foo.node', constants.RTLD_NOW)
```

@lovell

**Comment by lovell** [comment]
Interesting, I guess this might fail if a weak reference to an external symbol has been intentionally made via something like `__attribute__((weak))`.

https://en.wikipedia.org/wiki/Weak_symbol

**Comment by vweevers** [comment]
Reading `man ld.so(8)`, weak symbols don't apply to the dynamic linker:

> By default, when searching shared libraries to resolve a symbol reference, the dynamic linker will resolve to the first definition it finds.
> 
> Old glibc versions (before 2.2), provided a different behavior: if the linker found a symbol that was weak, it would remember that symbol and keep searching in the remaining shared libraries.  If it subsequently found a strong definition of the same symbol, then it would instead use that defi‐
nition.  (If no further symbol was found, then the dynamic linker would use the weak symbol that it initially found.)
> 
> The old glibc behavior was nonstandard.  (**Standard practice is that the distinction between weak and strong symbols should have effect only at static link time.**)  In glibc 2.2, the dynamic linker was modified to provide the current behavior (which was the behavior that was provided by most other implementations at that time).

Mac is probably a different story.

**Comment by lovell** [comment]
That's good, ignore my idle (weak?) thoughts.

It looks like `os.constants.dlopen` was added in Node.js 10 so we'd need to fallback to the existing `require` check, or wait until a semver major increment next year that drops Node.js 8 support.

**Comment by vweevers** [comment]
I'm not sure exactly in which cases we'd benefit from `RTLD_NOW`. Perhaps when attempting to load a glibc prebuild on alpine, for example? Need to test that.

**Comment by vweevers** [comment]
Probably not worth the effort and breakage.
