### ISSUE TITLE
Restore local prebuild option

### ISSUE THREAD

**Issue by ghost** [prebuild/prebuild-install#114]
The local prebuild feature appears to have been removed in version 5, specifically in this commit: https://github.com/prebuild/prebuild-install/commit/0593bf5ac5b331d9c8742e81e26866679b7d83d4

I'm bundling an NPM package that needs to be installable offline from a TGZ, since some users have firewall restrictions. One of the dependencies I'm bundling is `keytar`, which uses `prebuild-install` to install its native code.

With the local prebuild feature, I can easily make my package installable offline by adding the compiled native code for each platform to a "prebuilds" folder in my TGZ. With this feature removed in v5, it's a lot harder to do this as I need to add a preinstall script that copies the native code into the NPM cache, to fake out downloading it.

Since local prebuild seems like a useful feature for making packages installable offline, I'm not sure why it was considered unnecessary and removed. Please consider restoring this feature.

**Comment by vweevers** [comment]
I'm not sure either. Would welcome a PR to restore it, as an opt-in feature and provided that the implementation is simple. It does feel slightly out of scope to me, considering that `keytar` could be using [`prebuildify`](https://github.com/prebuild/prebuildify) instead.
