### ISSUE TITLE
v5.3.1 breaks compatibility with Node 4.x

### ISSUE THREAD

**Issue by emadum** [prebuild/prebuild-install#118]
Updating major versions for `simple-get` and `tar-fs` [here](https://github.com/prebuild/prebuild-install/commit/bd718e16a6ea51f6b5ea99e676a2a9e0b732d11b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R33) breaks compatibility with Node 4.x.

I realize that Node v4 support was dropped in v4.0.0 of this module. However things actually kept working until v5.3.1. This is an issue for e.g. [node-snappy](https://github.com/kesla/node-snappy/issues/183) which still supports Node 4.x.

[Pinning to 5.3.0 fixes](https://github.com/kesla/node-snappy/pull/184/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R23) the issue for node-snappy, but I think it would be nice to continue supporting Node 4.x while it's not too much of an inconvenience, or introduce a new major version to indicate that breaking changes were introduced via dependency update.

Pinning `simple-get` to `2.x` and `tar-fs` to `1.x` would allow master to continue working in Node 4.x.

**Comment by vweevers** [comment]
Pinning those, especially `tar-fs`, also means we lose bugfixes (in transitive dependencies). That said, I understand the need, and suggest we revisit this if and when we merge bugfixes or features here that are also important to node-snappy. Unless that's already true - see [changes since 5.3.1](https://github.com/prebuild/prebuild-install/compare/v5.3.1...v5.3.3).

**Comment by emadum** [comment]
That definitely makes sense, and I don't think those updates matter for node-snappy. That said, I do think it would be helpful to keep 5.x working for node 4, and put those dependency upgrades into a 6.0 release. If there are modules other than node-snappy with a `^(>=5, <5.3.1)` dependency, they will break unexpectedly in node 4.

**Comment by vweevers** [comment]
It's not completely unexpected, as we dropped 4 with a major bump and npm should warn about it:

https://github.com/prebuild/prebuild-install/blob/84e610b433b2f3ee486761e27139fa3f368135b4/package.json#L66-L68

I can't find it just now but there's also a related issue on one of the prebuild modules regarding node 6 support. We need to take some time to (re)consider our LTS policy. Will take your suggestion into consideration.
