### ISSUE TITLE
Incorrectly unpack tar.gz downloaded from bitbucket

### ISSUE THREAD

**Issue by zdm** [prebuild/prebuild-install#124]
When prebuild-install download archive (via simple-get) it adds header `Accept-Encoding: gzip, deflate`.
Bitbucket returns `tar.gz` files as is (because they are already gzipped), but with the content type `application/x-tar`.
So, if response content type is `application/x-tar` and `content-encoding` is `gzip` you shouldn't unzip request body, but save it as is with `tar.gz` extension.
Currently you unzip request body and save plain tar content as tar.gz that is leads to errors.

**Comment by zdm** [comment]
You can test using this link
https://bitbucket.org/softvisio/prebuild/raw/master/better-sqlite3/v7.1.0/better-sqlite3-v7.1.0-node-v83-linux-x64.tar.gz

**Comment by vweevers** [comment]
A possible fix on our end is to set `Accept-Encoding: identity`, overriding the default header of `simple-get`.

**Comment by zdm** [comment]
Yes, this will be correct solution, you don;t need http compression because tar.gz is already compressed.

**Comment by vweevers** [comment]
PR is welcome

**Comment by zdm** [comment]
The problem is more deep.
Bitbucket always returns `Content-Encoding: gzip`, regardless to the `Accept-Encoding` header.
`simple-get` have no option to skip body decompression.
What the sense to use `simple -get`? Your case is pretty simple, it will be faster to re-write this on pure node http, than make PR for 3-rd party packages and wait for a weeks until it will be accepted. 
What do you think?

**Comment by zdm** [comment]
Or more faster solution is to store content from bitbucketin cache  as tar and do not use intermediate zip stream.

**Comment by vweevers** [comment]
> Or more faster solution is to store content from bitbucketin cache as tar and do not use intermediate zip stream.

I would like to avoid logic specific to the bitbucket domain.

> You can test using this link
> https://bitbucket.org/softvisio/prebuild/raw/master/better-sqlite3/v7.1.0/better-sqlite3-v7.1.0-node-v83-linux-x64.tar.gz

I'm getting a 404 on that link, is it public?

**Comment by zdm** [comment]
repo was renamed, new url:

https://bitbucket.org/softvisio/node-prebuild/raw/master/better-sqlite3/v7.1.0/better-sqlite3-v7.1.0-node-v83-linux-x64.tar.gz

**Comment by vweevers** [comment]
It seems Bitbucket is at fault here, for not respecting `Accept-Encoding: identity`.

Perhaps we can work around it by using [`gunzip-maybe`](https://github.com/mafintosh/gunzip-maybe) instead of `zlib.createGunzip()` here:

https://github.com/prebuild/prebuild-install/blob/406b0513833be7c9e909128e642a42e82242f720/download.js#L87

**Comment by zdm** [comment]
I created PR for noDecompress option for simple-get. Let's wait several days.

**Comment by ralphtheninja** [comment]
@zdm You seem very keen on getting things fixed _now_ and not having to wait for weeks on everything. I can understand your frustration. Are you aware of that you can use your changes immediately and not having to wait? Just fork `prebuild-install` and use your fork of `simple-get` as a dependency until changes have been merged upstream.

**Comment by zdm** [comment]
@ralphtheninja  Thank you for advice. My personal opinion is that IT industry is degradates from year to year. Developers do not want to understand how code works, this is not required, if they just can find some shitty package in registry. 90% packages is complete shit with bad api, errors and tons of other dependencies with the same quality, like `lodash` or `isarray`. `prebuild-install` also has `isarray` as sub-dependency ;-).
Now we need to waste a weeks of life to approve small reasonable changes in dependency, that just performs simple http get request. `simple-get` maintainers will will gather a consultation and will research my PR, as if their product is a USA constitution. **I am sorry for this words**, but i am really tired from this. I don't try to offend @vweevers, perhaps use of `simple-get` is reasonable choice here. Please understand me correctly, I just want to describe whole picture.
Seems, that soon we will have `isarray` in it personal docker container.

**Comment by vweevers** [comment]
The alternative is to handle redirects, http vs https, timeouts and errors here instead of in `simple-get`, and then test and maintain those features. I love the npm ecosystem. Waiting for the upstream change is 100% worth it, for countless reasons that I do not want to rehash. I'm sorry you don't feel the same way. In any case, as @ralphtheninja said, you don't have to wait.

Please consider editing your comment. Calling packages X and Y "shit" is counterproductive. Keep in mind that we've been donating time to help you.

**Comment by zdm** [comment]
I removed my comment, it was not related to this issue.
Hope, that PR to simple-get will be accepted soon.
Thank you.

**Comment by zdm** [comment]
There is no interest to the PR in `simple-get` repo.
I can implement get request without `simple-get` if you will accept this PR.
Or we can use `node-fetch`, it is more powerful and has no dependencies.
What do  you think?

**Comment by vweevers** [comment]
> There is no interest to the PR

No response within 5 days does not mean there's no interest, because 5 days is nothing in volunteered open source time. So we will wait. That does not block you from using your own forks of `prebuild-install` and `simple-get`.

**Comment by zdm** [comment]
I need to use it with third-party module, so it can be installed only from the official source.
`node-fetch` has `"compress": false` option, that allows to get raw response body, so we can easily move to the `node-fetch`.
Also `node-fetch` has no deps and it is much popular and better maintained.
