### ISSUE TITLE
Legacy versions of mkdirp are no longer supported

### ISSUE THREAD

**Issue by humphreyn** [prebuild/prebuild-install#126]
Are there any plans to upgrade mkdirp to 1.x. as the current version is no longer supported?

**Comment by ralphtheninja** [comment]
Not until now :)

**Comment by vweevers** [comment]
We can either drop old node versions and use `fs.mkdir(.., { recursive: true })` but for now I'd prefer switching to https://github.com/mafintosh/mkdirp-classic

**Comment by ralphtheninja** [comment]
Why was it deprecated in the first place?

**Comment by vweevers** [comment]
Yeah, it works just fine

**Comment by ralphtheninja** [comment]
Ah, now I see. I didn't realize substacks version was forked by isaacs.

**Comment by humphreyn** [comment]
Big :+1:

Any idea when this might get released?

**Comment by ralphtheninja** [comment]
@humphreyn 5.3.6

**Comment by humphreyn** [comment]
@ralphtheninja , brilliant thank you
