### ISSUE TITLE
vulnerability: Remote Memory Exposure

### ISSUE THREAD

**Issue by amjedomar** [prebuild/prebuild-install#132]
To avoid [Remote Memory Exposure](https://www.npmjs.com/advisories/1555) vulnerability

please update `tar-fs` package

```
npm i tar-fs@2.1.1
```

**Comment by vweevers** [comment]
https://github.com/prebuild/prebuild-install/blob/9e62565f5847d5fad887112969c13df57e96f0a8/package.json#L35

**Comment by amjedomar** [comment]
Thanks for your help

delete `yarn.lock file` and run `yarn` fix the problem
