### ISSUE TITLE
Local file:// source for prebuilds?

### ISSUE THREAD

**Issue by jchook** [prebuild/prebuild-install#136]
Similar to this idea: https://github.com/mapbox/node-pre-gyp/issues/101

When building lightweight docker images, musl prebuilds are commonly unavailable, which triggers a `node-gyp rebuild`.

To speed up CI/CD flow, I would like to prebuild locally, store that in docker layer cache, then have prebuild-install to use that local prebuild as the "download" source for a subsequent `npm ci`.

Right now it seems that `leveldown_binary_host` (for example) does not support the `file://` protocol (which might be a neat way to support this feature), and I'm left with either [tricking prebuild-install](https://github.com/prebuild/prebuild-install/blob/9e62565f5847d5fad887112969c13df57e96f0a8/util.js#L74) into believing it already downloaded an unpublished prebuild, or serving the prebuild over HTTP.

Happy to contribute a PR.

**Comment by vweevers** [comment]
Related: https://github.com/prebuild/prebuild-install/issues/114

**Comment by jchook** [comment]
#114 is very interesting to me -- looks like there was a perfectly good way to do this before.

Should I submit a PR that simply reverts that deletion?

**Comment by jchook** [comment]
Seems we could reinstate most of the code removed in #114 verbatim to solve the issue. May want an env var to control the local prebuilds path.

Also the download paths contain an extra dir level for the version compared to the cache. Thinking that causes unnecessary complexity, considering that prebuild does not emit them in that dir structure.

**Comment by jchook** [comment]
Released in [6.1.0](https://github.com/prebuild/prebuild-install/releases/tag/v6.1.0) 🎉
