### ISSUE TITLE
handle app project package.json "cmake-js" field

### ISSUE THREAD

**Issue by bung87** [prebuild/prebuild-install#138]
see https://github.com/cmake-js/cmake-js#runtimes  

I know `prebuild-install` supported configure from cli env and `.npmrc` and app project `package.json` "config" field,
last time I configure from "config" field seems not work, don't know why.

also I suggest document it can configure from `.npmrc` and app project `package.json`

I also noticed `electron-builder` documented `Don’t use npm (neither .npmrc) for configuring electron headers. Use electron-builder node-gyp-rebuild instead.`  dont know if there's problem.

**Comment by vweevers** [comment]
From the description, I don't understand if this is a bug report, feature request or gap in documentation. Feel free to send a pull request with a concrete change.
