### ISSUE TITLE
Failed download for sqlite3 - Invalid URL template

### ISSUE THREAD

**Issue by ajfranzoia** [prebuild/prebuild-install#144]
After hours of debugging I was able to find out the problem between `pkg` and `sqlite3` not getting along.

I was getting this error when running `pkg` for an app that targets Linux/Win:
```
prebuild-install WARN install No prebuilt binaries found (target=v14.4.0 runtime=node arch=x64 libc= platform=linux)
> [debug] prebuild-install failed[/home/augusto/dev/mi-audit-upload-agent/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node]:
  Error: Command failed: /home/augusto/dev/mi-audit-upload-agent/node_modules/pkg/node_modules/.bin/prebuild-install -t v14.4.0 --platform linux --arch x64
prebuild-install WARN install No prebuilt binaries found (target=v14.4.0 runtime=node arch=x64 libc= platform=linux)

prebuild-install WARN install No prebuilt binaries found (target=v14.4.0 runtime=node arch=x64 libc= platform=win32)
> [debug] prebuild-install failed[/home/augusto/dev/mi-audit-upload-agent/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node]:
  Error: Command failed: /home/augusto/dev/mi-audit-upload-agent/node_modules/pkg/node_modules/.bin/prebuild-install -t v14.4.0 --platform win32 --arch x64
prebuild-install WARN install No prebuilt binaries found (target=v14.4.0 runtime=node arch=x64 libc= platform=win32)
```

I found out that the `sqlite3@v5.0.2` package.json declares the following binary lookup properties:
```json
  "binary": {
    "module_name": "node_sqlite3",
    "module_path": "./lib/binding/napi-v{napi_build_version}-{platform}-{arch}",
    "host": "https://mapbox-node-binary.s3.amazonaws.com",
    "remote_path": "./{name}/v{version}/{toolset}/",
    "package_name": "napi-v{napi_build_version}-{platform}-{arch}.tar.gz",
    "napi_versions": [
      3
    ]
  }
```

The placeholders `{napi_build_version}` and `{toolset}` don't seem to be yet supported, so the download URL ends up being `https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/{toolset}/napi-v{napi_build_version}-linux-x64.tar.gz` for a Linux target (instead of `https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-x64.tar.gz`). Naturally, the request will fail and the binary won't be downloaded.

On the other hand, `node-pre-gyp` manages to download the binary from the correct URL. The code used to generate the proper URL is this one https://github.com/mapbox/node-pre-gyp/blob/master/lib/util/versioning.js#L277.

Maybe we can port the missing logic into this library? I will glady submit a PR if someone points me out the right direction.

**Comment by vweevers** [comment]
How/where is `prebuild-install` used, if `sqlite` uses `node-pre-gyp` rather than `prebuild(-install)`?
