### ISSUE TITLE
Prebuild install does not work with scoped packages where the scope name has a dash

### ISSUE THREAD

**Issue by Valandur** [prebuild/prebuild-install#147]
According to the [npm docs](https://docs.npmjs.com/cli/v7/using-npm/scope) a scope can contain `URL-safe characters, no leading dots or underscores`. This includes dashes and/or underscores within the name (e.g. `@scope-name/package`).

However, the following line in utils uses the `\w` regex match, which only matches `[a-zA-Z0-9_]`, which does not include dashes. This makes prebuild-install look for the binaries in the wrong location (e.g.  `https://github.com/scope-name/package/releases/download/v1.0.0/@scope-name/package-v1.0.0-node-v83-win32-x64.tar.gz`) which obviously doesn't work.

https://github.com/prebuild/prebuild-install/blob/2e3fedbe5363d510b778529d1eaef8b17692b78e/util.js#L8

**Comment by vweevers** [comment]
PR is welcome
