### ISSUE TITLE
[regression] modules are always compiling

### ISSUE THREAD

**Issue by piranna** [prebuild/prebuild-install#15]
After inclusion of #8 and #12, now I'm getting the modules to always get compiling and not downloading. I could see the point of force the compiling on development environment when `prebuild-install` is a direct dependency of the project where `npm install` is executed (but I disagree on this and I think `--no-prebuild` flag should be used instead), the problem is when using a dependency that makes uses of `prebuild-install`, since that dependency will gets compiled too, making `prebuild-install` mostly useless.

I see two solutions here:
1. revert #12 and force users to use `--no-prebuild`
2. check we are on the root project and only in that case ignore the prebuilds, but still use them in other case

I would do both because sometimes I want to test locally that the prebuild images works correctly before publishing the module to npm, so I would revert #12 and make `--no-prebuild` and opt-in, and also do the check because the flag would be applied to all the executions also on internal dependencies, that's what we are not interested about.

As a side note, since #12 changed the current behaviour of `prebuild-install` it should have been a major version, by the way. I think we could republish the module as-is with version 2.0.0 and remove 1.1.0 from npm so people can stick with 1.0.2, but I think this feature should have more discussion before adding it back...

**Comment by mathiask88** [comment]
Hm.. that is odd.

```js
if (!(typeof pkg._from === 'string')) {...
```
is only true if `prebuild-install` is NO dependency (`npm i`inside `prebuild-install`root dir) and the second case
```js
if (pkg._from.length > 4 && pkg._from.substr(0, 4) === 'git+') {...
```
is only true if it is a GIT dependency. But apparently there went something wrong.

**Comment by ralphtheninja** [comment]
@piranna Why is it failing?

**Comment by piranna** [comment]
If you look some lines up,

pkg = require(path.resolve('package.json'))

that use always the package.json file of the project root (cwd), no matter
how deep in the dependency tree prebuild-install is.

**Comment by ralphtheninja** [comment]
@piranna @mafintosh added you to npm
@mathiask88 Could not find you on npm

**Comment by piranna** [comment]
Thank you.

**Comment by ralphtheninja** [comment]
@piranna Fwiw, I think it's better if we can fix the problem and release a new patch instead of doing the unpublishing dance

**Comment by piranna** [comment]
I suppose. I think the fix would be easy (search for the package.json of
the parent project, or if not use prebuild-install one if it's the root
project), but it keeps the problem when it's a direct dependency, since I
want to test it download correctly and I think the ones who want to force a
build should use the --pre-build flag, so I think #12 needs to be reverted
too.

**Comment by ralphtheninja** [comment]
@piranna Mind making some PRs for what needs to be done in your opinion?

**Comment by piranna** [comment]
> @piranna Mind making some PRs for what needs to be done in your opinion?

https://github.com/mafintosh/prebuild-install/pull/16

Here you have a fix for the problem of not downloading on the internal dependencies.

It keeps to discuss what to do when executing `npm install` in an in-development project, I think it should download the prebuild if available, if you don't want to download it you can set a different version on the `package.json` file (for example a `-pre` one) or use the already available `--no-prebuild` flag instead of compile it automatically (it's said, revert #12).

**Comment by ralphtheninja** [comment]
> It keeps to discuss what to do when executing npm install in an in-development project, I think it should download the prebuild if available, if you don't want to download it you can set a different version on the package.json file (for example a -pre one) or use the already available --no-prebuild flag instead of compile it automatically (it's said, revert #12).

+1 I'm fine with either or. It's more important for me that we don't break your shit :)

**Comment by piranna** [comment]
> +1 I'm fine with either or. It's more important to me that we don't break your shit :)

It's not my shit, it's more a KISS principle, in fact my "shit" is only to be able to test that prebuild images download and works correctly.

**Comment by piranna** [comment]
I've found the problem I was having was not related to the cwd and in fact it was being used the correct one insead of project root, but the problem still arises because I'm using Github as source of my dependencies. I think by removing this branch of the if on #12 and force compile only for local copies of the source code would be just enough (although I would remove that too...).

**Comment by piranna** [comment]
Any update on this? I need to get stuck on version 1.0.2 of `prebuild-install`...

**Comment by ralphtheninja** [comment]
No update. I suggest you make PR since you already know what the problem is and how to fix it :)

**Comment by piranna** [comment]
I have been thinking a bit about this problem, and I think the most simple and least surprising behaviour would be to try always to download the prebuild images except if the `--no-prebuild` flag is used, because it would be possible that someone downloads a project directly from Github (downloading a tarball or using `git clone`) and install it and want to use its prebuild images. if we consider this use case as "developer mode" and we want people to use `npm` for doing the install in all the cases (also for applications and global libraries), then we could simply check for the existence of the `pkg._from` field and in that case try to download the prebuild image by using the `version` field defined in the `package.json`, and do directly the build in any other case. What do you think? I believe this would be the most simple way `prebuild-install` could do its job...

**Comment by piranna** [comment]
I have been checking the code and definitely the regression was introduced on #12. The check done there using `pkg._from` to know if the install is being done using `npm` is not bad, but the check after that about if the package is being installed from a `git` repository (and the one that has introduced this regression) is flaky. What about packages installed from github but using the https clone url instead of `git`? And what about the packaged defined with a local path or using a `file:` scheme? That ones would get downloaded too... That's why I've done the next patch to make `prebuild-install` to try to download the prebuild image in all the cases if it has being installed using `npm`:

```diff
diff --git a/server.js b/server.js
index 14536c1..fdc541d 100755
--- a/server.js
+++ b/server.js
@@ -51,15 +51,12 @@ var opts = extend(rc, {pkg: pkg, log: log})
 if (!pkg._from) {
   log.info('install', 'installing from project directory, skipping download')
   process.exit(3)
-} else if (pkg._from.length > 4 && pkg._from.substr(0, 4) === 'git+') {
-  log.info('install', 'installing from git repository, skipping download')
-  process.exit(4)
 }
 
 download(opts, function (err) {
   if (err) {
     log.warn('install', err.message)
-    return process.exit(5)
+    return process.exit(4)
   }
 
   log.info('install', 'Prebuild successfully installed!')
```

This way, if someone wants to force the build in development, it just only need to use the already available `--no-prebuild` flag. If you find it ok, I can be able to do a pull-request for it, or we could comment any other solution.

**Comment by ahornerr** [comment]
👍  on this. We're seeing prebuilds being skipped when downloading from git. See: https://github.com/couchbase/couchnode/pull/74

**Comment by mathiask88** [comment]
Is this still a problem? I have to admit that the git check is flaky (does not fetch the user/project style), but what I don't get is what version shall prebuild-install download for a git dependency?

**Comment by piranna** [comment]
Lately I'm seeing the problem, but also I have had NodeOS a little bit unatended... I think the expected behaviour would be to compile the module when it's a git checkout, but download it when the it's a git dependency. Probably would be enough to just check for a `.git` folder...

**Comment by mathiask88** [comment]
@ahornerr I think that is because u are using `pnpm` for me 
`npm i couchbase/couchnode#c5f933bd6c845bcad6bf85df11a5e8250aaa72e0 --verbose --target=6.1.0`
works fine and downloads the prebuild.

**Comment by mathiask88** [comment]
Is this still an issue? I think everyone is pleased with the current behavior? I'm just asking because we are facing a new major.
