### ISSUE TITLE
Cannot specify binary_host for packages starting with @

### ISSUE THREAD

**Issue by tom-boothman** [prebuild/prebuild-install#152]
Packages with names starting with @ such as
https://github.com/abandonware/node-bluetooth-hci-socket/blob/master/package.json and https://github.com/serialport/node-serialport/blob/master/packages/bindings/package.json can't have their binary_host override specified.

"@serialport/bindings" wants a variable called _serialport_bindings_binary_host according to https://github.com/prebuild/prebuild-install/blob/master/util.js#L64

Any npm config variable that starts with a _ just seems to vanish whether you specify it from .npmrc or as a command line parameter to npm i.

Steps to reproduce

```
npm_config__serialport_bindings_binary_host="https://whatever/" npm i @serialport/bindings

or

echo '_serialport_bindings_binary_host="https://whatever/' >> .npmrc
echo 'test=5' >> .npmrc
npm i @serialport/bindings
npm config list
```

**Comment by vweevers** [comment]
Done in https://github.com/prebuild/prebuild-install/pull/153.
