### ISSUE TITLE
Consider inlining `noop-logger`

### ISSUE THREAD

**Issue by alexdima** [prebuild/prebuild-install#154]
Hi, we are shipping your node module with VS Code, so I wanted to start by thanking you for your work!

According to https://github.com/segmentio/noop-logger/issues/2 , the `noop-logger` repository is no longer maintained and the recommendation is to simply inline the code where needed. 

The background is that we end up also shipping `noop-logger` with VS Code and are having trouble figuring out how to attribute the npm module correctly (i.e. the license is missing a Copyright statement, which is an integral part of the MIT license -- https://opensource.org/licenses/MIT).

**Comment by ralphtheninja** [comment]
@alexdima That sounds like a good idea. PR welcome!
