### ISSUE TITLE
--path option writing to wrong destination

### ISSUE THREAD

**Issue by dunkmann00** [prebuild/prebuild-install#157]
When I tried to set the `--path` option when installing a prebuild, it would append the `path` value twice.

For example:
`--path path/to/directory/`
`unpack resolved to .../path/to/directory/path/to/directory/`

I think this is because in `bin.js` a new process is spawned in the `path` directory when one is present:
https://github.com/prebuild/prebuild-install/blob/cca87fbe261756569da5a7022b28eb8da392d9be/bin.js#L20

And then in `download.js` the `path` is appended onto the current directory, which it shouldn't because we are already in the directory of the `path`:
https://github.com/prebuild/prebuild-install/blob/cca87fbe261756569da5a7022b28eb8da392d9be/download.js#L106

So I think in dowload we wouldn't want to check for `path` again, just always use `'.'`?

This just pertains to relative paths.

**Comment by dunkmann00** [comment]
It looks like the `opts.path` option is also used here:
https://github.com/prebuild/prebuild-install/blob/cca87fbe261756569da5a7022b28eb8da392d9be/download.js#L97
which is what actually controls where the prebuilt binary is saved.

**Comment by vweevers** [comment]
If we make `rc.path` an absolute path - i.e. `rc.path = path.resolve(rc.path)` - then it wouldn't matter that `rc.path` is reused multiple times. Might be redundant, but we'd avoid having to refactor.
