### ISSUE TITLE
Resolve vulnerability in dependencies (simple-get < 4.0.1)

### ISSUE THREAD

**Issue by timondev** [prebuild/prebuild-install#172]
https://security.snyk.io/vuln/SNYK-JS-SIMPLEGET-2361683

update `simple-get` dependency from `^4.0.0` to at least `^4.0.1` to negate security risk.

```package.json
"dependencies": {
    "simple-get": "^4.0.0" 
},
```

to

```package.json
"dependencies": {
    "simple-get": "^4.0.1" 
},
```

it seems that this is not a breaking change (aka no further changes were made to `simple-get`)

**Comment by vweevers** [comment]
https://github.com/prebuild/prebuild-install/pull/167#issuecomment-1023074227
