### ISSUE TITLE
Please update simple-get dependency to resolve security issue.

### ISSUE THREAD

**Issue by kevintechie** [prebuild/prebuild-install#173]
Simple-get has resolved a cookie leak issue. Please update dependent version to resolve high vulnerability issue: https://github.com/advisories/GHSA-wpg7-2c88-r8xv.

**Comment by vweevers** [comment]
https://github.com/prebuild/prebuild-install/pull/167#issuecomment-1023074227.

Please search other issues before opening a new issue. This is the 6th duplicate request. Thanks!
