### ISSUE TITLE
npm_config_* variables are not available in npm v7+ which breaks prebuild platform overrides

### ISSUE THREAD

**Issue by pimterry** [prebuild/prebuild-install#174]
I use `npm_config_platform` to cross-install prebuilt dependencies in my application releases. By setting `npm_config_platform=win32` for example, when I run `npm install` in a project with dependencies using prebuild-install, I get the correct node modules to deploy my application on Windows, even if I'm building on Linux.

This is nicely documented here in the README:

> When prebuild-install is run via an npm script, options --build-from-source, --debug, --download, --target, --runtime, --arch and --platform may be passed through via arguments given to the npm command.
> 
> Alternatively you can set environment variables npm_config_build_from_source=true, npm_config_platform, npm_config_arch, npm_config_target and npm_config_runtime.

Unfortunately, from npm v7 onwards, this no longer works. Almost all `npm_config_*` variables are no longer provided to scripts: https://github.com/npm/rfcs/blob/main/implemented/0021-reduce-lifecycle-script-environment.md. These values are no longer set by default, and even if they're explicitly set as variables in the parent environment, they're not passed through.

That makes it impossible to control the platform used for prebuild-install in subdependencies when running `npm install` in a project.

Would you be open to adding a separate non-npm environment variable, so this works again? `PREBUILD_INSTALL_PLATFORM` for example would work perfectly.

You might want to investigate other uses of `npm_config_*` here too, since as far as I can tell almost all of them are no longer useful in any recent npm releases.

**Comment by vweevers** [comment]
We handled this in https://github.com/prebuild/prebuild-install/pull/128 and have unit tests for env vars too, so I'm not sure where the gap is.

**Comment by pimterry** [comment]
:flushed: Turns out this is my fault - the dependency I'm using is using prebuild-install v5, where it doesn't work. Using the new npm overrides setup if I force them to use v7 by adding:

```json
"overrides": {
  "prebuild-install": "^7.0.0"
}
```

then everything works perfectly!

I don't really understand how this can possibly work though, even after reading through #128. From the NPM RFC, I understood that they were dropping all `npm_config_*` environment variables, so there shouldn't be any way to get at those environment variables from npm's parent environment at all when launched from an npm script. How does this work?

Well done anyway :+1: I'll close this now.

**Comment by vweevers** [comment]
> How does this work?

The key part is this:

> Remove all `npm_config_*` values from the script lifecycle environment _except_:
> - \[..]
> - Environment variables corresponding to any non-default config values.
