### ISSUE TITLE
Can't install package in private network

### ISSUE THREAD

**Issue by khabirovar** [prebuild/prebuild-install#178]
Hi!
I try install kerberos@1.1.4 in private network.
I already upload in nexus prebuild for kerberos
and add string for using this prebuilds:
   kerberos_binary_host=http://nexus/repository/local-repo/npm/kerberos-v1.1.4-node-v72-linux-x64.tar.gz
in .npmrc 

But i have error 
[91mprebuild-install WARN install No prebuilt binaries found (target=12.22.5 runtime=node arch=x64 libc= platform=linux)
08:16:24   [0m [91mgyp [0m [91m WARN install got an error, rolling back install
[kerberos-v1.1.4-node-v72-linux-x64.tar.gz](https://github.com/prebuild/prebuild-install/files/8338891/kerberos-v1.1.4-node-v72-linux-x64.tar.gz)

Maybe i use wrong prebuilds
How can i generate right prebuild 
or maybe need add something .npmrc

**Comment by lovell** [comment]
Did you see https://github.com/prebuild/prebuild-install#custom-binaries ?

> Note that the package version subpath and file name will still be appended.

**Comment by khabirovar** [comment]
Yeah. but didn't help.
I add kerberos_binary_host=http://<path_to_local_nexus>/kerveros-v1.1.4-node-v72-linux-x64.tar.gz.
and get error
![kerberos](https://user-images.githubusercontent.com/2740475/164541259-186ee55b-6037-4ff9-89e7-9d04e1441c2d.jpg)

i try bunch of prebuilds in tar.gz format 
![kerberos2](https://user-images.githubusercontent.com/2740475/164541434-7e0e2912-ae15-4177-b0cf-f36fb6362111.jpg)
some generated via prebuild utility some taken from npm cache 

fyi 
i try install this package on host without access to internet

**Comment by lovell** [comment]
Did you read and comprehend https://github.com/prebuild/prebuild-install#custom-binaries including the example it provides?

Please note how the version and filename will be appended to the base URL you provide in the environment variable.

For example, if you set:
```
kerberos_binary_host=http://nexus/repository/local-repo/npm/kerberos-v1.1.4-node-v72-linux-x64.tar.gz
```
then the following URL will be used:
```
http://nexus/repository/local-repo/npm/kerberos-v1.1.4-node-v72-linux-x64.tar.gz/v1.1.4/kerberos-v1.1.4-node-v72-linux-x64.tar.gz
```
which is probably not what you meant.

If you set:
```
kerberos_binary_host=http://nexus/repository/local-repo/npm
```
then the following URL will be used:
```
http://nexus/repository/local-repo/npm/v1.1.4/kerberos-v1.1.4-node-v72-linux-x64.tar.gz
```
which is closer to what you want, but you'll need to create versioned subdirectories to match.
