### ISSUE TITLE
prebuild-install WARN install No prebuilt binaries found

### ISSUE THREAD

**Issue by rassokhina-e** [prebuild/prebuild-install#188]
Hi there!

I try to build the Windows release of an Electron app. There is an issue, which I cannot fix:
```
prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=6.1.2 runtime=electron arch=x86 libc= platform=win32)
```

Can you please help me to investigate it?
<img width="1305" alt="Screenshot 2023-01-31 at 5 21 57 PM" src="https://user-images.githubusercontent.com/31901584/215772567-f9748722-ec01-4c2d-ada4-c9e2c343c283.png">

**Comment by mafintosh** [comment]
You should open this issue on the package you are trying to build. Prebuild just manages the prebuilds of which you have none. If for some reason, this is a prebuild build, feel free to re-open.
