### ISSUE TITLE
why doesn't it honor NPM_CONFIG_CACHE?

### ISSUE THREAD

**Issue by dotysan** [prebuild/prebuild-install#193]
https://docs.npmjs.com/cli/v10/using-npm/config#environment-variables

I was overriding ~/.npm/ with NPM_CONFIG_CACHE environment variable. Everything went swimmingly for all other npm actions. But this package does not honor NPM_CONFIG_CACHE. Is this a bug?

Workaround was quite simple:
`export npm_config_cache="$NPM_CONFIG_CACHE"`

It appears to be related to this. https://github.com/npm/npm/issues/14528

**Comment by mathiask88** [comment]
I think it is already answered in the [post](https://github.com/npm/npm/issues/14528#issuecomment-258547044) you mentioned.
NPM sets lowercase env variables and node prefers the lowercase version if there are two. We do honor this env variable as you can see [here](https://github.com/prebuild/prebuild-install/blob/master/util.js#L83).

NPM docs quote
> However, please note that inside [scripts](https://docs.npmjs.com/cli/v10/using-npm/scripts) npm will set its own environment variables and Node will prefer those lowercase versions over any uppercase ones that you might set. For details see [this issue](https://github.com/npm/npm/issues/14528).
