### ISSUE TITLE
Check remote prebuild before using cache

### ISSUE THREAD

**Issue by piranna** [prebuild/prebuild-install#28]
Check if the published prebuild is newer in date than our local cache and invalidate it. This is useful when developing in local, since the local one could be corrupted.

**Comment by mathiask88** [comment]
There is an undocumented `nolocal` argument https://github.com/mafintosh/prebuild-install/blob/master/download.js#L22

Maybe you can use that for development.

**Comment by mathiask88** [comment]
@piranna Does this work out for you? Should we document it?

**Comment by piranna** [comment]
> @piranna Does this work out for you? Should we document it?

I haven't tested it.
