### ISSUE TITLE
Environmental variable options not passed through npm

### ISSUE THREAD

**Issue by clehner** [prebuild/prebuild-install#43]
I am working on a [wrapper for npm](https://viewer.scuttlebot.io/%25IdZKhhIsSEw4i3MFLRmkBfvIUHujkGlAl7pwWbigQVQ%3D.sha256) where I want to be able to run npm with either a command-line flag or environmental variable to tell `prebuild-install` to download prebuilds from a URL other than GitHub. I see that `prebuild-install` uses `rc` and a `download` config option to set the download URL. Setting the environmental variable `prebuild-install_download` to my custom URL template works when running `prebuild-install` from the command-line - however, it does not work when it is run via an `npm` script (`npm run install`). From some debugging, I found that `npm` seems to not pass through env vars with a hyphen, and since `prebuild-install`s `rc` prefix has a hyphen, none of its env vars get passed through. Setting `download=...` in `~/.prebuild-installrc` works, but I would prefer not to touch the file system.

Would a PR be welcomed here that added a way to pass through the `download` option from `npm`'s cli args or env vars, in a non-breaking way? I am thinking the simplest way would be to use an env var without a hypen, like `prebuildinstall_download`, as a default for the `download` config option in `rc.js`. Or is there a better alternative that I am missing?

**Comment by ralphtheninja** [comment]
@clehner :wave: 

`rc` has support for cli arguments as well, see https://github.com/dominictarr/rc#standards (using `minimist`). Have you tried that approach? If that doesn't cut it, we can always make a PR to tweak it to your needs.

**Comment by ralphtheninja** [comment]
I might have misunderstood your use case a bit, maybe cli arguments doesn't cut it since I figure the configuration needs to be passed to `prebuild-install` seamlessly, given that you are making a npm wrapper, that I take it "should just work" out of the box?

**Comment by clehner** [comment]
Hi @ralphtheninja

For my use case which involves spawning `npm`, using a cli arg would be about as good as using an env var, except I guess it wouldn't work for `yarn` or other possible npm clients. But maybe those would allow passing through the `prebuild-install_download` env var so this wouldn't matter.

Using `--download=...` works when running `prebuild-install` directly, but when it is run as an `npm` script, the cli args passed to npm don't get passed through. However, `rc.js` here already extracts some args from the args passed to `npm`, via `env.npm_config_argv`. So I could add some handling to extract and use `--download=...` argument there also. Do you think that be acceptable?
