### ISSUE TITLE
How do you force prebuild-install to NOT compile from source/ALWAYS download prebuild binaries?

### ISSUE THREAD

**Issue by ian-axiadids** [prebuild/prebuild-install#47]
Really, I'd just like to force prebuild-install to NEVER skip the prebuilt option (they exist for a reason, after all!)

**Comment by mathiask88** [comment]
If a binary is available ´prebuild-install´ will always use it. Compiling from source is fallback only on user side. Do you have an example?

**Comment by ian-axiadids** [comment]
Sorry, yes. To clarify, I am attempting to use prebuild while installing a node module from a Git(Hub) repository instead of NPM. If I do not install the module directly from NPM (the original module does not provide prebuilt binaries) then I receive a line like the following:

```
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info install installing from git repository, skipping download.
```

I have not found any way to force the use of prebuilt binaries, despite both trying with binaries commited in `prebuilds` and with prebuild's native `prebuild -u <token>` GitHub release upload. If there is a way to do so already, we can update the documentation to make this clearer.

Just to clarify, the module is included as a dependency under `git+<repository>`/`file:<path>`, but both methods cause it to skip retrieval of the (most certainly available) prebuilt binaries.

**Comment by ralphtheninja** [comment]
I think I know what you mean now. The "skipping download" thing is a feature used for when developing modules. But in your case this feature gets in your way since you are actually using `git:` or `file:` based dependencies and you will basically never get the any prebuilts. Correct?

**Comment by mathiask88** [comment]
Why don't you make a PR to make https://github.com/santigimeno/node-pcsclite prebuild ready? Maybe you can convince him that using prebuild is a cool thing? :)

**Comment by vweevers** [comment]
> The "skipping download" thing is a feature used for when developing modules. But in your case this feature gets in your way since you are actually using git: or file: based dependencies and you will basically never get any prebuilts.

This case also falls under "development". A git based dependency is mutable, so it can't have prebuilds.

> Why don't you make a PR to make https://github.com/santigimeno/node-pcsclite prebuild ready? Maybe you can convince him that using prebuild is a cool thing? :)

👍

**Comment by mathiask88** [comment]
> This case also falls under "development". A git based dependency is mutable, so it can't have prebuilds.

True.. The only thing we could do is to check if the github url is a tagged one and search the releases for that tagged version?!

**Comment by ian-axiadids** [comment]
> I think I know what you mean now. The "skipping download" thing is a feature used for when developing modules. But in your case this feature gets in your way since you are actually using git: or file: based dependencies and you will basically never get any prebuilts. Correct?

This is correct.

> Why don't you make a PR to make https://github.com/santigimeno/node-pcsclite prebuild ready? Maybe you can convince him that using prebuild is a cool thing? :)

Strange, I don't recall mentioning that module? ;)

Unfortunately, that would only solve our most obvious issue: getting the module itself loaded. We have a multi-stage build process for a cross-platform app that, ideally, should only have to be run on a Linux machine. Amongst various other issues, we want to make certain we're using our QA-tested binaries.

> > This case also falls under "development". A git based dependency is mutable, so it can't have prebuilds.
>
> True.. The only thing we could do is to check if the github url is a tagged one and search the releases for that tagged version?!

I don't think changing the default behavior here is worth the effort; instead, I would propose a new flag that forces `prebuild-install` to ignore those checks. If accidental developer misuse is a worry, we could add warnings to alert the developer.

The code looks simple enough to modify. If there's not an existing method to do this, then I'll work on a pull request to add this functionality? :)

**Comment by ralphtheninja** [comment]
> The code looks simple enough to modify. If there's not an existing method to do this, then I'll work on a pull request to add this functionality? :)

:+1:

**Comment by ian-axiadids** [comment]
@ralphtheninja The PR has been made when you have the chance to review it.

**Comment by ralphtheninja** [comment]
@ian-axiadids Yep, just noticed it! Fixing borked travis first.
