### ISSUE TITLE
Tests should run on OSX and Windows

### ISSUE THREAD

**Issue by ralphtheninja** [prebuild/prebuild-install#57]
Since `prebuild-install` is meant for installing prebuilts for all platforms, we should really run the tests on all platforms as well and not only on linux.

- [x] osx
- [x] windows

**Comment by mathiask88** [comment]
@ralphtheninja Can you upload Win/OSX prebuilts for `a-native-module` then? I will have a look at the tests on windows tomorrow.

**Comment by ralphtheninja** [comment]
> @ralphtheninja Can you upload Win/OSX prebuilts for a-native-module then? I will have a look at the tests on windows tomorrow.

Will do!

**Comment by ralphtheninja** [comment]
Done. Let me know if I missed any.

**Comment by mathiask88** [comment]
Tests are all fine on my windows machine. If you want you can add this repo to appveyor and activate OSX for travis.

**Comment by ralphtheninja** [comment]
@vweevers Feel like taking lead on AppVeyor? 😀

**Comment by mathiask88** [comment]
https://github.com/prebuild/prebuild-install/pull/61
