### ISSUE TITLE
time to drop node 0.10 and 0.12 now?

### ISSUE THREAD

**Issue by ralphtheninja** [prebuild/prebuild-install#58]
[![](https://api.gh-polls.com/poll/01C4HDT9DR0563PXNV9YKM08YG/Yes)](https://api.gh-polls.com/poll/01C4HDT9DR0563PXNV9YKM08YG/Yes/vote)
[![](https://api.gh-polls.com/poll/01C4HDT9DR0563PXNV9YKM08YG/No)](https://api.gh-polls.com/poll/01C4HDT9DR0563PXNV9YKM08YG/No/vote)

**Comment by lgeiger** [comment]
👍
