### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by ralphtheninja** [prebuild/prebuild-install#65]

**Comment by ralphtheninja** [comment]
Gah, I've kept this hanging for ages.

**Comment by MadLittleMods** [comment]
Are there any breaking changes from v4 to v5? https://github.com/prebuild/prebuild-install/compare/062cb4153dd9b08e39d8ae34a66052340ea226e8...master

**Comment by vweevers** [comment]
@MadLittleMods node 4 was dropped, that's it.

**Comment by vweevers** [comment]
Done in https://github.com/prebuild/prebuild-install/pull/129
