### ISSUE TITLE
Custom binaries host not used when the package's name contains a dash

### ISSUE THREAD

**Issue by Kasalehlia** [prebuild/prebuild-install#96]
I am building an electron app unsing electron-builder. If I want to use custom binaries for a dependency, e.g. `node-hid` I am setting `node-hid_binary_host = http://localhost:1234/` in `.npmrc`, and npm confirms this is set.
It seems that at some point the dashes in the variable names are replaced with underscores, so prebuild-install can not find the variable and does not use the alternate server.
By patching the `getHostMirrorUrl` function to replace dashes with underscores in the pkg.name I was able to get the desired behaviour, but I'm not sure this will not cause collisions at some point.

**Comment by vweevers** [comment]
> By patching the `getHostMirrorUrl` function to replace dashes with underscores in the pkg.name I was able to get the desired behaviour, but I'm not sure this will not cause collisions at some point.

Can you send a PR so we can see what that looks like?

Perhaps we can read both the original env var and the underscored variant.

**Comment by Kasalehlia** [comment]
https://github.com/prebuild/prebuild-install/pull/97

**Comment by vweevers** [comment]
Hm, [npm docs](https://docs.npmjs.com/misc/config#per-package-config-settings) state that you can use `:` to separate the package name and config key. If so, maybe the PR is not needed.

Can you try `npm config set node-hid:binary_host http://localhost:1234/`?

**Comment by Kasalehlia** [comment]
That also results an underscore in the package name.

**Comment by vweevers** [comment]
OK. Was worth a shot :)

**Comment by vweevers** [comment]
I did a test on a mock package and replacing dashes indeed seems to be builtin npm behavior. I'm OK with the proposed fix (though we have 67 dependents with a dash in their name). The only use case I can think of that would break, is manually setting a `npm_config_package-name_..` environment variable but I prefer following npm's behavior.
