### ISSUE TITLE
Add support for build_from_source=true inside .npmrc

### ISSUE THREAD

**Issue by adipascu** [prebuild/prebuild-install#98]
I have a `.npmrc` file similar to this one:
```
runtime=electron
disturl=https://atom.io/download/electron
target=3.1.8
build_from_source=true
```
`build_from_source=true` forces a full rebuild while using node-pre-gyp ([it happens here](https://github.com/mapbox/node-pre-gyp/blob/67c156ee45804f1aeca2dfed0f3939ebe04b89ad/lib/install.js#L196)).
More information can be found on the web under the [npm_config_build_from_source](https://www.google.com/search?gws_rd=cr&gl=US&q=npm_config_build_from_source) env variable.

**Comment by vweevers** [comment]
Are you up for making a PR?

**Comment by adipascu** [comment]
@vweevers PR is done at #99
